I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/classes/Bullet.rpy", line 3, in <module>
    class Bullet:
  File "game/classes/Bullet.rpy", line 4, in Bullet
    def __init__(self, pos=Vector(0, 0), vel=Vector(0, 0), size=Vector(10, 10)):
NameError: name 'Vector' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/bootstrap.py", line 305, in bootstrap
    renpy.main.main()
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/main.py", line 365, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/script.py", line 756, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn)
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/script.py", line 448, in finish_load
    node.early_execute()
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/ast.py", line 878, in early_execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/fiendchain/Downloads/sze-the-game-orphan/renpy/python.py", line 1764, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/classes/Bullet.rpy", line 3, in <module>
    class Bullet:
  File "game/classes/Bullet.rpy", line 4, in Bullet
    def __init__(self, pos=Vector(0, 0), vel=Vector(0, 0), size=Vector(10, 10)):
NameError: name 'Vector' is not defined

Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.13.2919
 
