I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00gamemenu.rpy", line 173, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 173, in <module>
    $ ui.interact()
  File "game/screens/inventory.rpy", line 65, in execute
    screen gui_tooltip(item=False):
  File "game/screens/inventory.rpy", line 65, in execute
    screen gui_tooltip(item=False):
  File "game/screens/inventory.rpy", line 66, in execute
    if item:
  File "game/screens/inventory.rpy", line 67, in execute
    vbox:
  File "game/screens/inventory.rpy", line 71, in execute
    for stat, value in item.stat.iteritems():
AttributeError: 'RevertableSet' object has no attribute 'iteritems'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00gamemenu.rpy", line 173, in script
    $ ui.interact()
  File "/home/fiendchain/Downloads/sze-the-game/renpy/ast.py", line 826, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/python.py", line 1764, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00gamemenu.rpy", line 173, in <module>
    $ ui.interact()
  File "/home/fiendchain/Downloads/sze-the-game/renpy/ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/core.py", line 2553, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/core.py", line 2821, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/core.py", line 495, in visit_all
    d.visit_all(callback)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/screen.py", line 401, in visit_all
    callback(self)
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/core.py", line 2821, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/screen.py", line 411, in per_interact
    self.update()
  File "/home/fiendchain/Downloads/sze-the-game/renpy/display/screen.py", line 580, in update
    self.screen.function(**self.scope)
  File "game/screens/inventory.rpy", line 65, in execute
    screen gui_tooltip(item=False):
  File "game/screens/inventory.rpy", line 65, in execute
    screen gui_tooltip(item=False):
  File "game/screens/inventory.rpy", line 66, in execute
    if item:
  File "game/screens/inventory.rpy", line 67, in execute
    vbox:
  File "game/screens/inventory.rpy", line 71, in execute
    for stat, value in item.stat.iteritems():
  File "<screen language>", line 71, in <module>
AttributeError: 'RevertableSet' object has no attribute 'iteritems'

Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.13.2919
sze-the game 0.0
